// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 7 --osr 2700 --hinf 1.1 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 298.0 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 7;
localparam integer DSM_N_G  = 3;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:6] = '{34'sd0, 34'sd38, 34'sd1950, 34'sd63541, 34'sd1425091, 34'sd22013366, 34'sd217826786};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd0};
localparam signed [34-1:0] DSM_C [0:6] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:2] = '{34'sd239, 34'sd799, 34'sd1309};
