// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 8 --osr 2700 --hinf 1.3 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 390.2 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 8;
localparam integer DSM_N_G  = 4;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:7] = '{34'sd10, 34'sd538, 34'sd14291, 34'sd242941, 34'sd2886212, 34'sd24559597, 34'sd146525455, 34'sd562928183};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd5};
localparam signed [34-1:0] DSM_C [0:7] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:3] = '{34'sd0, 34'sd372, 34'sd908, 34'sd1337};
