// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 6 --osr 2700 --hinf 1.5 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 336.3 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 6;
localparam integer DSM_N_G  = 3;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:5] = '{34'sd60945, 34'sd1311682, 34'sd13459314, 34'sd84520348, 34'sd344176290, 34'sd868389725};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd30472};
localparam signed [34-1:0] DSM_C [0:5] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:2] = '{34'sd0, 34'sd595, 34'sd1255};
