// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 8 --osr 2700 --hinf 1.1 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 321.6 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 8;
localparam integer DSM_N_G  = 4;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:7] = '{34'sd0, 34'sd1, 34'sd37, 34'sd1654, 34'sd52719, 34'sd1211198, 34'sd19612449, 34'sd205501977};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd0};
localparam signed [34-1:0] DSM_C [0:7] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:3] = '{34'sd0, 34'sd372, 34'sd908, 34'sd1337};
