// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// CIFB ΔΣ modulator coefficients, order=7, OSR=2700,
// Hinf=1.5, opt=2, f0=0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 379.5 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.20 (total 24 bits).

localparam integer DSM_ORDER = 7;
localparam integer DSM_N_G  = 3;
localparam integer DSM_COEFF_W = 24;
localparam integer DSM_COEFF_FRAC = 20;

localparam signed [24-1:0] DSM_A [0:6] = '{24'sd4, 24'sd124, 24'sd1703, 24'sd14662, 24'sd85467, 24'sd338520, 24'sd848676};
localparam signed [24-1:0] DSM_B [0:0] = '{24'sd2};
localparam signed [24-1:0] DSM_C [0:6] = '{24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576};
localparam signed [24-1:0] DSM_G [0:2] = '{24'sd0, 24'sd1, 24'sd1};
