// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// CIFB ΔΣ modulator coefficients, order=2, OSR=2700,
// Hinf=1.5, opt=0, f0=0.0.
// Predicted peak SQNR (analytic, sine at umax): 147.1 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.20 (total 24 bits).

localparam integer DSM_ORDER = 2;
localparam integer DSM_N_G  = 1;
localparam integer DSM_COEFF_W = 24;
localparam integer DSM_COEFF_FRAC = 20;

localparam signed [24-1:0] DSM_A [0:1] = '{24'sd226881, 24'sd812491};
localparam signed [24-1:0] DSM_B [0:0] = '{24'sd226881};
localparam signed [24-1:0] DSM_C [0:1] = '{24'sd1048576, 24'sd1048576};
localparam signed [24-1:0] DSM_G [0:0] = '{24'sd0};
