// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 8 --osr 2700 --hinf 1.4 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 406.8 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 8;
localparam integer DSM_N_G  = 4;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:7] = '{34'sd68, 34'sd2914, 34'sd61389, 34'sd824005, 34'sd7705275, 34'sd51466183, 34'sd240449967, 34'sd721840323};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd34};
localparam signed [34-1:0] DSM_C [0:7] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:3] = '{34'sd0, 34'sd372, 34'sd908, 34'sd1337};
