// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// CIFB ΔΣ modulator coefficients, order=4, OSR=2700,
// Hinf=1.5, opt=2, f0=0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 247.0 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.20 (total 24 bits).

localparam integer DSM_ORDER = 4;
localparam integer DSM_N_G  = 2;
localparam integer DSM_COEFF_W = 24;
localparam integer DSM_COEFF_FRAC = 20;

localparam signed [24-1:0] DSM_A [0:3] = '{24'sd6440, 24'sd67854, 24'sd323526, 24'sd844656};
localparam signed [24-1:0] DSM_B [0:0] = '{24'sd3220};
localparam signed [24-1:0] DSM_C [0:3] = '{24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576};
localparam signed [24-1:0] DSM_G [0:1] = '{24'sd0, 24'sd1};
