// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// Re-run synthesize_dsm.py with different --order/--osr/--hinf to regenerate;
// dac.v is parametric in ORDER/N_G and adapts to whatever this file declares.
// Synthesis inputs: --order 5 --osr 2700 --hinf 1.5 --opt 2 --f0 0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 294.2 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.30 (total 34 bits).

localparam integer DSM_ORDER = 5;
localparam integer DSM_N_G  = 2;
localparam integer DSM_COEFF_W = 34;
localparam integer DSM_COEFF_FRAC = 30;

localparam signed [34-1:0] DSM_A [0:4] = '{34'sd703821, 34'sd10928870, 34'sd79388443, 34'sd339885122, 34'sd867246730};
localparam signed [34-1:0] DSM_B [0:0] = '{34'sd351911};
localparam signed [34-1:0] DSM_C [0:4] = '{34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824, 34'sd1073741824};
localparam signed [34-1:0] DSM_G [0:1] = '{34'sd421, 34'sd1194};
