// Auto-generated by scripts/synthesize_dsm.py — do not edit.
// CIFB ΔΣ modulator coefficients, order=8, OSR=2700,
// Hinf=1.5, opt=2, f0=0.0.
// STF(DC) gain (b₁/a₁): 0.5000 (digital FS → -6.02 dBFS analog).
// Predicted peak SQNR (analytic, sine at umax): 419.2 dB.
// Max stable DC input (umax): nan FS.
// Q-format: signed Q3.20 (total 24 bits).

localparam integer DSM_ORDER = 8;
localparam integer DSM_N_G  = 4;
localparam integer DSM_COEFF_W = 24;
localparam integer DSM_COEFF_FRAC = 20;

localparam signed [24-1:0] DSM_A [0:7] = '{24'sd0, 24'sd10, 24'sd177, 24'sd1999, 24'sd15653, 24'sd87329, 24'sd340039, 24'sd849077};
localparam signed [24-1:0] DSM_B [0:0] = '{24'sd0};
localparam signed [24-1:0] DSM_C [0:7] = '{24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576, 24'sd1048576};
localparam signed [24-1:0] DSM_G [0:3] = '{24'sd0, 24'sd0, 24'sd1, 24'sd1};
